import Head from 'next/head'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import Sidebar from '../components/sidebar/Sidebar'

import {useAuthState} from 'react-firebase-hooks/auth'
import {auth} from '../firebase/firebaseapp'

export default function Home() {
const [user]=useAuthState(auth);

  return (
    <div className={styles.container}>
      <Head>
        <title>Ping Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style.main>
          <Sidebar user={user}/>
      </style.main>
    </div>
  )
}
export async function getServerSideProps(context){

  return {props:{}}
}
const style={
  main:styled.main`
  width:100%;
  height:100vh;
  /* background-color: rgba(0,0,0,1); */
  display: grid;
  grid-template-columns: 1fr 2fr;
  @media (max-width:700px) {
    grid-template-columns: 1fr;
  }
  `,
}